function render(){const h=hero();$('#cycleLabel').textContent=cycleText();$('#heroTone').textContent=h.tone;$('#heroTitle').textContent=h.title;$('#heroDetail').textContent=h.detail;$('#foodBalance').textContent=$('#fundFood').textContent=yen(state.balances.food);$('#pocketBalance').textContent=$('#fundPocket').textContent=yen(state.balances.pocket);$('#spendable').textContent=yen(state.balances.food+state.balances.pocket);renderFunds();renderTransactions()}
function fundMarkup(f,actions=false){const p=f.target>0?Math.min(100,Math.round(f.balance/f.target*100)):0;return `<div class="item"><div class="row"><div><b>${escapeHtml(f.name)}</b><div class="muted">${yen(f.balance)}${f.target?` / ${yen(f.target)}`:''}${f.deadline?` ・ ${f.deadline}`:''}</div></div><span class="pill">${f.target?p+'%':'目標未設定'}</span></div>${f.target?`<div class="progress"><span style="width:${p}%"></span></div>`:''}${actions?`<div class="fundActions"><button data-fund-expense="${f.id}">支出</button><button data-fund-edit="${f.id}">編集</button></div>`:''}</div>`}
function renderFunds(){$('#homeFunds').innerHTML=state.funds.length?state.funds.slice(0,4).map(f=>fundMarkup(f)).join(''):'<div class="empty">目的別資金はありません。</div>';$('#fundCards').innerHTML=state.funds.length?state.funds.map(f=>`<section class="card" style="margin-bottom:12px">${fundMarkup(f,true)}</section>`).join(''):'<section class="card empty">目的別資金はありません。</section>';$$('[data-fund-edit]').forEach(b=>b.onclick=()=>openFundEdit(b.dataset.fundEdit));$$('[data-fund-expense]').forEach(b=>b.onclick=()=>openFundExpense(b.dataset.fundExpense))}
function txMarkup(t){const sign=t.kind==='income'?'+':'-';const cls=t.kind==='income'?'':'negative';return `<div class="item row"><div><b>${escapeHtml(t.memo||t.category)}</b><div class="muted">${t.date} ・ ${escapeHtml(t.category)}</div></div><div class="${cls}">${sign}${yen(t.amount)}</div></div>`}
function renderTransactions(){const tx=[...state.transactions].sort((a,b)=>b.createdAt-a.createdAt);$('#recentTransactions').innerHTML=tx.length?tx.slice(0,5).map(txMarkup).join(''):'<div class="empty">まだ支出はありません。</div>';$('#allTransactions').innerHTML=tx.length?tx.map(txMarkup).join(''):'<div class="empty">履歴はありません。</div>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openSheet(id){$('#'+id).classList.add('open')}function closeSheet(el){el.closest('.sheetWrap').classList.remove('open')}
$$('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.open==='fundSheet')resetFundForm();if(b.dataset.open==='balanceSheet'){ $('#balanceFood').value=state.balances.food;$('#balancePocket').value=state.balances.pocket }openSheet(b.dataset.open)});$$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b));$$('.sheetWrap').forEach(w=>w.addEventListener('click',e=>{if(e.target===w)w.classList.remove('open')}));
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));$('#quickExpense').style.display=b.dataset.view==='homeView'?'':'none'});
$('#quickExpense').onclick=()=>openSheet('expenseSheet');$('#expenseDate').value=today();
function recentDuplicate(candidate){const last=[...state.transactions].sort((a,b)=>b.createdAt-a.createdAt)[0];if(!last)return false;return last.kind==='expense'&&last.amount===candidate.amount&&last.category===candidate.category&&last.memo===candidate.memo&&last.date===candidate.date&&(Date.now()-last.createdAt)<10000}
$('#expenseForm').onsubmit=e=>{e.preventDefault();const v=amount($('#expenseAmount').value);const category=$('#expenseCategory').value;const memo=$('#expenseMemo').value.trim();const date=$('#expenseDate').value;if(v===null)return alert('金額は1円以上の整数で入力してください。');if(!category)return alert('使うお金を選んでください。');const key=category==='食費・日用品'?'food':'pocket';if(v>state.balances[key])return alert(`${category}の残高を超えています。`);const tx={id:crypto.randomUUID?.()||'tx-'+Date.now(),date,amount:v,category,memo,kind:'expense',createdAt:Date.now()};if(recentDuplicate(tx))return alert('同じ支出が直前に登録されています。二重登録を防止しました。');if(!confirm(`${memo||category}\n${category}から ${yen(v)}\n\n記録しますか？`))return;state.balances[key]-=v;state.transactions.push(tx);save();render();e.target.reset();$('#expenseDate').value=today();$('#expenseSheet').classList.remove('open');toast('支出を記録しました')};
function resetFundForm(){$('#fundSheetTitle').textContent='目的別資金を追加';$('#fundEditId').value='';$('#fundName').value='';$('#fundBalance').value='';$('#fundTarget').value='';$('#fundDeadline').value='';$('#deleteFund').style.display='none'}
function openFundEdit(id){const f=state.funds.find(x=>x.id===id);if(!f)return;$('#fundSheetTitle').textContent='目的別資金を編集';$('#fundEditId').value=f.id;$('#fundName').value=f.name;$('#fundBalance').value=f.balance;$('#fundTarget').value=f.target||'';$('#fundDeadline').value=f.deadline||'';$('#deleteFund').style.display='block';openSheet('fundSheet')}
$('#saveFund').onclick=()=>{const name=$('#fundName').value.trim();const balance=amount($('#fundBalance').value,{allowZero:true});const target=amount($('#fundTarget').value||0,{allowZero:true});if(!name)return alert('名前を入力してください。');if(balance===null||target===null)return alert('金額は0円以上の整数で入力してください。');const id=$('#fundEditId').value;if(id){const f=state.funds.find(x=>x.id===id);Object.assign(f,{name,balance,target,deadline:$('#fundDeadline').value||''})}else state.funds.push({id:crypto.randomUUID?.()||'fund-'+Date.now(),name,balance,target,deadline:$('#fundDeadline').value||''});save();render();$('#fundSheet').classList.remove('open');toast('目的別資金を保存しました')};
$('#deleteFund').onclick=()=>{const id=$('#fundEditId').value;const f=state.funds.find(x=>x.id===id);if(!f)return;if(!confirm(`${f.name}を削除しますか？`))return;state.funds=state.funds.filter(x=>x.id!==id);save();render();$('#fundSheet').classList.remove('open')};
function openFundExpense(id){const f=state.funds.find(x=>x.id===id);if(!f)return;$('#fundExpenseId').value=f.id;$('#fundExpenseInfo').innerHTML=`<b>${escapeHtml(f.name)}</b><br>現在残高 ${yen(f.balance)}`;$('#fundExpenseAmount').value='';$('#fundExpenseMemo').value='';$('#fundExpenseDate').value=today();openSheet('fundExpenseSheet')}
$('#saveFundExpense').onclick=()=>{const f=state.funds.find(x=>x.id===$('#fundExpenseId').value);const v=amount($('#fundExpenseAmount').value);if(!f||v===null)return alert('金額を確認してください。');if(v>f.balance)return alert('現在残高を超えています。');const memo=$('#fundExpenseMemo').value.trim()||`${f.name}から支出`;if(!confirm(`${f.name}から ${yen(v)} 支出しますか？`))return;f.balance-=v;state.transactions.push({id:crypto.randomUUID?.()||'tx-'+Date.now(),date:$('#fundExpenseDate').value||today(),amount:v,category:f.name,memo,kind:'expense',createdAt:Date.now()});save();render();$('#fundExpenseSheet').classList.remove('open');toast('支出を記録しました')};
$('#saveBalances').onclick=()=>{const food=amount($('#balanceFood').value,{allowZero:true}),pocket=amount($('#balancePocket').value,{allowZero:true});if(food===null||pocket===null)return alert('0円以上の整数で入力してください。');if(!confirm(`食費・日用品 ${yen(food)}、お小遣い ${yen(pocket)} に設定しますか？`))return;state.balances={food,pocket};save();render();$('#balanceSheet').classList.remove('open');toast('残高を更新しました')};
$('#exportBtn').onclick=()=>{save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`okane-compass-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const next=normalizeState(parsed);if(!confirm('現在のデータをバックアップ内容で置き換えますか？'))return;state=next;save();render();toast('バックアップを読み込みました')}catch(err){alert('バックアップ形式が正しくありません。')}finally{e.target.value=''}};
$('#clearTransactions').onclick=()=>{if(!confirm('支出履歴だけを削除しますか？残高は変更しません。'))return;state.transactions=[];save();render();toast('履歴を削除しました')};
$('#resetAll').onclick=()=>{if(!confirm('全データを初期化します。この操作は取り消せません。'))return;state=clone(DEFAULT_STATE);save();render();toast('初期化しました')};
save();render();