let calendarCursor=new Date();let selectedDate=today();
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function switchView(id){$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$('#quickExpense').style.display=id==='homeView'?'':'none';if(id==='calendarView')renderCalendar()}
function render(){const h=hero();$('#cycleLabel').textContent=cycleText();$('#heroTone').textContent=h.tone;$('#heroTitle').textContent=h.title;$('#heroDetail').textContent=h.detail;$('#foodBalance').textContent=$('#fundFood').textContent=yen(state.balances.food);$('#pocketBalance').textContent=$('#fundPocket').textContent=yen(state.balances.pocket);$('#spendable').textContent=yen(state.balances.food+state.balances.pocket);renderFunds();renderTransactions();renderAllocations();renderUpcoming();renderFixed();renderCalendar()}
function fundMarkup(f,actions=false){const p=f.target>0?Math.min(100,Math.round(f.balance/f.target*100)):0;return `<div class="item"><div class="row"><div><b>${escapeHtml(f.name)}</b><div class="muted">${yen(f.balance)}${f.target?` / ${yen(f.target)}`:''}${f.deadline?` ・ ${f.deadline}`:''}</div></div><span class="pill">${f.target?p+'%':'目標未設定'}</span></div>${f.target?`<div class="progress"><span style="width:${p}%"></span></div>`:''}${actions?`<div class="fundActions"><button data-fund-expense="${f.id}">支出</button><button data-fund-edit="${f.id}">編集</button></div>`:''}</div>`}
function renderFunds(){$('#homeFunds').innerHTML=state.funds.length?state.funds.slice(0,4).map(f=>fundMarkup(f)).join(''):'<div class="empty">目的別資金はありません。</div>';$('#fundCards').innerHTML=state.funds.length?state.funds.map(f=>`<section class="card" style="margin-bottom:12px">${fundMarkup(f,true)}</section>`).join(''):'<section class="card empty">目的別資金はありません。</section>';$$('[data-fund-edit]').forEach(b=>b.onclick=()=>openFundEdit(b.dataset.fundEdit));$$('[data-fund-expense]').forEach(b=>b.onclick=()=>openFundExpense(b.dataset.fundExpense))}
function txMarkup(t){const sign=t.kind==='income'?'+':'-';return `<div class="item row"><div><b>${escapeHtml(t.memo||t.category)}</b><div class="muted">${t.date} ・ ${escapeHtml(t.category)}${t.source&&t.source!=='app'?` ・ ${escapeHtml(t.source)}`:''}</div></div><div class="${t.kind==='income'?'':'negative'}">${sign}${yen(t.amount)}</div></div>`}
function renderTransactions(){const tx=[...state.transactions].sort((a,b)=>b.createdAt-a.createdAt);$('#recentTransactions').innerHTML=tx.length?tx.slice(0,5).map(txMarkup).join(''):'<div class="empty">まだ支出はありません。</div>';$('#allTransactions').innerHTML=tx.length?tx.map(txMarkup).join(''):'<div class="empty">履歴はありません。</div>'}
function renderUpcoming(){const list=[...state.calendarEvents].filter(e=>e.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4);$('#upcomingEvents').innerHTML=list.length?list.map(e=>`<div class="item row"><div><b>${escapeHtml(e.title)}</b><div class="muted">${e.date} ・ ${e.type}</div></div><b>${e.amount?yen(e.amount):''}</b></div>`).join(''):'<div class="empty">今後の予定はありません。</div>'}
function renderAllocations(){const list=[...state.allocations].sort((a,b)=>b.createdAt-a.createdAt);$('#allocationHistory').innerHTML=list.length?list.slice(0,8).map(a=>`<div class="item"><div class="row"><b>${a.date} 入金 ${yen(a.income)}</b><span class="pill">${a.items.length}項目</span></div><div class="muted">${a.items.filter(x=>x.amount>0).map(x=>`${escapeHtml(x.name)} ${yen(x.amount)}`).join(' ・ ')}</div></div>`).join(''):'<div class="empty">振り分け履歴はありません。</div>'}
function openSheet(id){$('#'+id).classList.add('open')}
function closeSheet(el){el.closest('.sheetWrap').classList.remove('open')}
$$('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.open==='fundSheet')resetFundForm();if(b.dataset.open==='balanceSheet'){ $('#balanceFood').value=state.balances.food;$('#balancePocket').value=state.balances.pocket }if(b.dataset.open==='allocationSheet')prepareAllocation();if(b.dataset.open==='eventSheet'){$('#eventDate').value=selectedDate||today()}if(b.dataset.open==='fixedSheet')renderFixed();openSheet(b.dataset.open)});$$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b));$$('.sheetWrap').forEach(w=>w.addEventListener('click',e=>{if(e.target===w)w.classList.remove('open')}));$$('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewJump));
$('#quickExpense').onclick=()=>openSheet('expenseSheet');$('#expenseDate').value=today();
function recentDuplicate(c){const last=[...state.transactions].sort((a,b)=>b.createdAt-a.createdAt)[0];return !!last&&last.kind==='expense'&&last.amount===c.amount&&last.category===c.category&&last.memo===c.memo&&last.date===c.date&&(Date.now()-last.createdAt)<10000}
$('#expenseForm').onsubmit=e=>{e.preventDefault();const v=amount($('#expenseAmount').value),category=$('#expenseCategory').value,memo=$('#expenseMemo').value.trim(),date=$('#expenseDate').value;if(v===null)return alert('金額は1円以上の整数で入力してください。');if(!category)return alert('使うお金を選んでください。');const key=category==='食費・日用品'?'food':'pocket';if(v>state.balances[key])return alert(`${category}の残高を超えています。`);const tx={id:uid('tx'),date,amount:v,category,memo,kind:'expense',source:state.pendingShortcut?'shortcut':'app',createdAt:Date.now()};if(recentDuplicate(tx))return alert('同じ支出が直前に登録されています。');if(!confirm(`${memo||category}\n${category}から ${yen(v)}\n\n記録しますか？`))return;state.balances[key]-=v;state.transactions.push(tx);state.pendingShortcut=null;save();render();e.target.reset();$('#expenseDate').value=today();$('#expenseSheet').classList.remove('open');history.replaceState({},'',location.pathname);toast('支出を記録しました')};
function resetFundForm(){$('#fundSheetTitle').textContent='目的別資金を追加';$('#fundEditId').value='';$('#fundName').value='';$('#fundBalance').value='';$('#fundTarget').value='';$('#fundDeadline').value='';$('#deleteFund').style.display='none'}
function openFundEdit(id){const f=state.funds.find(x=>x.id===id);if(!f)return;$('#fundSheetTitle').textContent='目的別資金を編集';$('#fundEditId').value=f.id;$('#fundName').value=f.name;$('#fundBalance').value=f.balance;$('#fundTarget').value=f.target||'';$('#fundDeadline').value=f.deadline||'';$('#deleteFund').style.display='block';openSheet('fundSheet')}
$('#saveFund').onclick=()=>{const name=$('#fundName').value.trim(),balance=amount($('#fundBalance').value,{allowZero:true}),target=amount($('#fundTarget').value||0,{allowZero:true});if(!name||balance===null||target===null)return alert('入力内容を確認してください。');const id=$('#fundEditId').value;if(id)Object.assign(state.funds.find(x=>x.id===id),{name,balance,target,deadline:$('#fundDeadline').value||''});else state.funds.push({id:uid('fund'),name,balance,target,deadline:$('#fundDeadline').value||''});save();render();$('#fundSheet').classList.remove('open');toast('目的別資金を保存しました')};
$('#deleteFund').onclick=()=>{const id=$('#fundEditId').value,f=state.funds.find(x=>x.id===id);if(!f||!confirm(`${f.name}を削除しますか？`))return;state.funds=state.funds.filter(x=>x.id!==id);save();render();$('#fundSheet').classList.remove('open')};
function openFundExpense(id){const f=state.funds.find(x=>x.id===id);if(!f)return;$('#fundExpenseId').value=f.id;$('#fundExpenseInfo').innerHTML=`<b>${escapeHtml(f.name)}</b><br>現在残高 ${yen(f.balance)}`;$('#fundExpenseAmount').value='';$('#fundExpenseMemo').value='';$('#fundExpenseDate').value=today();openSheet('fundExpenseSheet')}
$('#saveFundExpense').onclick=()=>{const f=state.funds.find(x=>x.id===$('#fundExpenseId').value),v=amount($('#fundExpenseAmount').value);if(!f||v===null||v>f.balance)return alert('金額を確認してください。');if(!confirm(`${f.name}から ${yen(v)} 支出しますか？`))return;f.balance-=v;state.transactions.push({id:uid('tx'),date:$('#fundExpenseDate').value||today(),amount:v,category:f.name,memo:$('#fundExpenseMemo').value.trim()||`${f.name}から支出`,kind:'expense',source:'app',createdAt:Date.now()});save();render();$('#fundExpenseSheet').classList.remove('open');toast('支出を記録しました')};
$('#saveBalances').onclick=()=>{const food=amount($('#balanceFood').value,{allowZero:true}),pocket=amount($('#balancePocket').value,{allowZero:true});if(food===null||pocket===null)return alert('0円以上の整数で入力してください。');if(!confirm(`食費・日用品 ${yen(food)}、お小遣い ${yen(pocket)} に設定しますか？`))return;state.balances={food,pocket};save();render();$('#balanceSheet').classList.remove('open');toast('残高を更新しました')};
function prepareAllocation(){$('#allocationIncome').value='';$('#allocationFood').value=0;$('#allocationPocket').value=0;$('#allocationNote').value='';$('#allocationFunds').innerHTML=state.funds.map(f=>`<div class="field"><label>${escapeHtml(f.name)}</label><input type="number" min="0" value="0" data-allocation-fund="${f.id}"></div>`).join('')}
$('#copyAllocationPrompt').onclick=async()=>{const income=amount($('#allocationIncome').value);if(income===null)return alert('入金額を入力してください。');const text=allocationPrompt(income);try{await navigator.clipboard.writeText(text);toast('相談文をコピーしました')}catch{prompt('この相談文をコピーしてください',text)}};
$('#applyAllocation').onclick=()=>{const income=amount($('#allocationIncome').value);if(income===null)return alert('入金額を入力してください。');const items=[{targetId:'food',name:'食費・日用品',amount:amount($('#allocationFood').value||0,{allowZero:true})},{targetId:'pocket',name:'お小遣い',amount:amount($('#allocationPocket').value||0,{allowZero:true})},...$$('[data-allocation-fund]').map(i=>({targetId:i.dataset.allocationFund,name:state.funds.find(f=>f.id===i.dataset.allocationFund)?.name||'',amount:amount(i.value||0,{allowZero:true})}))];if(items.some(x=>x.amount===null))return alert('金額を確認してください。');const total=items.reduce((s,x)=>s+x.amount,0);if(total>income)return alert('振り分け合計が入金額を超えています。');if(!confirm(`入金 ${yen(income)} のうち ${yen(total)} を反映しますか？`))return;state.balances.food+=items[0].amount;state.balances.pocket+=items[1].amount;items.slice(2).forEach(x=>{const f=state.funds.find(y=>y.id===x.targetId);if(f)f.balance+=x.amount});state.allocations.push({id:uid('allocation'),date:today(),income,items,note:$('#allocationNote').value.trim(),createdAt:Date.now()});save();render();$('#allocationSheet').classList.remove('open');toast('振り分けを反映しました')};
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$('#monthLabel').textContent=`${y}年 ${m+1}月`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let html='<div class="muted">日</div><div class="muted">月</div><div class="muted">火</div><div class="muted">水</div><div class="muted">木</div><div class="muted">金</div><div class="muted">土</div>';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');const ev=state.calendarEvents.filter(e=>e.date===ds);html+=`<button class="calCell ${d.getMonth()!==m?'mutedDay':''} ${ds===selectedDate?'selected':''}" data-cal-date="${ds}"><b>${d.getDate()}</b><div class="calDots">${ev.slice(0,4).map(()=>'<span class="calDot"></span>').join('')}</div></button>`}$('#calendarGrid').innerHTML=html;$$('[data-cal-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.calDate;renderCalendar()});$('#selectedDateLabel').textContent=`${selectedDate} の予定`;const list=state.calendarEvents.filter(e=>e.date===selectedDate);$('#selectedDateEvents').innerHTML=list.length?list.map(e=>`<div class="item row"><div><b>${escapeHtml(e.title)}</b><div class="muted">${e.type}${e.memo?` ・ ${escapeHtml(e.memo)}`:''}</div></div><div><b>${e.amount?yen(e.amount):''}</b><button class="linkBtn" data-delete-event="${e.id}">削除</button></div></div>`).join(''):'<div class="empty">予定はありません。</div>';$$('[data-delete-event]').forEach(b=>b.onclick=()=>{if(confirm('この予定を削除しますか？')){state.calendarEvents=state.calendarEvents.filter(e=>e.id!==b.dataset.deleteEvent);save();render()}})}
$('#prevMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};
$('#saveEvent').onclick=()=>{const title=$('#eventTitle').value.trim(),date=$('#eventDate').value,v=amount($('#eventAmount').value||0,{allowZero:true});if(!title||!date||v===null)return alert('入力内容を確認してください。');state.calendarEvents.push({id:uid('event'),date,title,amount:v,type:$('#eventType').value,memo:$('#eventMemo').value.trim(),fundId:''});save();render();$('#eventSheet').classList.remove('open');toast('予定を追加しました')};
function renderFixed(){$('#fixedList').innerHTML=state.fixedExpenses.map(f=>`<div class="item row"><div><b>${escapeHtml(f.name)}</b><div class="muted">${escapeHtml(f.category)}</div></div><div><b>${yen(f.amount)}</b><button class="linkBtn" data-use-fixed="${f.id}">使う</button><button class="linkBtn" data-delete-fixed="${f.id}">削除</button></div></div>`).join('')||'<div class="empty">固定支出はありません。</div>';$$('[data-use-fixed]').forEach(b=>b.onclick=()=>{const f=state.fixedExpenses.find(x=>x.id===b.dataset.useFixed);$('#expenseAmount').value=f.amount;$('#expenseCategory').value=f.category;$('#expenseMemo').value=f.name;$('#fixedSheet').classList.remove('open');openSheet('expenseSheet')});$$('[data-delete-fixed]').forEach(b=>b.onclick=()=>{state.fixedExpenses=state.fixedExpenses.filter(x=>x.id!==b.dataset.deleteFixed);save();renderFixed()})}
$('#addFixed').onclick=()=>{const name=$('#fixedName').value.trim(),v=amount($('#fixedAmount').value);if(!name||v===null)return alert('入力内容を確認してください。');state.fixedExpenses.push({id:uid('fixed'),name,amount:v,category:$('#fixedCategory').value});save();$('#fixedName').value='';$('#fixedAmount').value='';renderFixed();toast('固定支出を追加しました')};
$('#shortcutHelp').onclick=()=>alert('ショートカットから次のURL形式で開いてください。\n\nhttps://match0618.github.io/okane-compass/?amount=850&category=食費・日用品&memo=昼ごはん&date=2026-07-30&source=voice\n\nアプリで確認後に登録されます。');
$('#themeSelect').value=applyTheme();$('#themeSelect').onchange=e=>applyTheme(e.target.value);matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if($('#themeSelect').value==='system')applyTheme('system')});
$('#exportBtn').onclick=()=>{save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`okane-compass-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const next=normalizeState(JSON.parse(await file.text()));if(!confirm('現在のデータを置き換えますか？'))return;state=next;save();render();toast('バックアップを読み込みました')}catch{alert('バックアップ形式が正しくありません。')}finally{e.target.value=''}};$('#clearTransactions').onclick=()=>{if(confirm('支出履歴だけを削除しますか？')){state.transactions=[];save();render();toast('履歴を削除しました')}};$('#resetAll').onclick=()=>{if(confirm('全データを初期化しますか？')){state=clone(DEFAULT_STATE);save();render();toast('初期化しました')}};
const shortcut=parseShortcut();if(shortcut){state.pendingShortcut=shortcut;save();$('#expenseAmount').value=shortcut.amount;$('#expenseCategory').value=['食費・日用品','お小遣い'].includes(shortcut.category)?shortcut.category:'食費・日用品';$('#expenseMemo').value=shortcut.memo;$('#expenseDate').value=shortcut.date;openSheet('expenseSheet')}
save();applyTheme();render();
