'use strict';
const STORAGE_KEY='okane_compass_v2';
const BROKEN_KEY='okane_compass_broken_backup_v2';
const THEME_KEY='okane_compass_theme';
const MAX_AMOUNT=100000000;
const clone=v=>JSON.parse(JSON.stringify(v));
const DEFAULT_STATE={version:2,balances:{food:0,pocket:0},funds:[{id:'trip',name:'旅行費',balance:0,target:0,deadline:''},{id:'pass',name:'定期券',balance:0,target:54310,deadline:''},{id:'emergency',name:'生活防衛資金',balance:0,target:300000,deadline:''},{id:'cohabit',name:'同棲資金',balance:0,target:1000000,deadline:''}],transactions:[],allocations:[],calendarEvents:[],fixedExpenses:[{id:'cafeteria',name:'会社食堂',amount:450,category:'食費・日用品'},{id:'coffee',name:'コーヒー',amount:150,category:'お小遣い'}],pendingShortcut:null,updatedAt:''};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const uid=p=>(crypto.randomUUID?.()||`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`);
function amount(value,{allowZero=false}={}){const n=Number(value);if(!Number.isFinite(n)||!Number.isInteger(n))return null;if(n<0||n>MAX_AMOUNT)return null;if(!allowZero&&n===0)return null;return n}
function safeDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:''}
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:{};const out=clone(DEFAULT_STATE);out.version=2;out.balances.food=amount(s?.balances?.food,{allowZero:true})??0;out.balances.pocket=amount(s?.balances?.pocket,{allowZero:true})??0;out.funds=Array.isArray(s.funds)?s.funds.map((f,i)=>({id:String(f.id||uid(`fund-${i}`)),name:String(f.name||'目的別資金').slice(0,30),balance:amount(f.balance,{allowZero:true})??0,target:amount(f.target,{allowZero:true})??0,deadline:safeDate(f.deadline)})):clone(DEFAULT_STATE.funds);out.transactions=Array.isArray(s.transactions)?s.transactions.map((t,i)=>({id:String(t.id||uid(`tx-${i}`)),date:safeDate(t.date)||today(),amount:amount(t.amount)??0,category:String(t.category||''),memo:String(t.memo||'').slice(0,80),kind:t.kind==='income'?'income':'expense',source:String(t.source||'app'),createdAt:Number(t.createdAt)||Date.now()})).filter(t=>t.amount>0):[];out.allocations=Array.isArray(s.allocations)?s.allocations.map(a=>({id:String(a.id||uid('allocation')),date:safeDate(a.date)||today(),income:amount(a.income)??0,items:Array.isArray(a.items)?a.items.map(x=>({targetId:String(x.targetId||''),name:String(x.name||''),amount:amount(x.amount,{allowZero:true})??0})):[],note:String(a.note||'').slice(0,300),createdAt:Number(a.createdAt)||Date.now()})).filter(a=>a.income>0):[];out.calendarEvents=Array.isArray(s.calendarEvents)?s.calendarEvents.map(e=>({id:String(e.id||uid('event')),date:safeDate(e.date)||today(),title:String(e.title||'予定').slice(0,40),amount:amount(e.amount,{allowZero:true})??0,type:['income','bill','goal','event'].includes(e.type)?e.type:'event',fundId:String(e.fundId||''),memo:String(e.memo||'').slice(0,100)})):[];out.fixedExpenses=Array.isArray(s.fixedExpenses)?s.fixedExpenses.map(f=>({id:String(f.id||uid('fixed')),name:String(f.name||'固定支出').slice(0,30),amount:amount(f.amount)??0,category:['食費・日用品','お小遣い'].includes(f.category)?f.category:'食費・日用品'})).filter(f=>f.amount>0):clone(DEFAULT_STATE.fixedExpenses);out.pendingShortcut=s.pendingShortcut&&typeof s.pendingShortcut==='object'?s.pendingShortcut:null;out.updatedAt=new Date().toISOString();return out}
function load(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return clone(DEFAULT_STATE);try{return normalizeState(JSON.parse(raw))}catch(e){localStorage.setItem(BROKEN_KEY,raw);return clone(DEFAULT_STATE)}}
let state=load();
function save(){state=normalizeState(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function cycleText(){const d=new Date(),day=d.getDate();const end=day<=24?new Date(d.getFullYear(),d.getMonth(),24):new Date(d.getFullYear(),d.getMonth()+1,24);const days=Math.max(0,Math.ceil((end-new Date(d.getFullYear(),d.getMonth(),d.getDate()))/86400000));return `給料サイクル 25日〜24日・残り${days}日`}
function hero(){const spend=state.balances.food+state.balances.pocket;let tone='今日の確認',title=`あと使えるのは ${yen(spend)}`,detail=`食費・日用品 ${yen(state.balances.food)}、お小遣い ${yen(state.balances.pocket)}。`;const upcoming=[...state.calendarEvents].filter(e=>e.date>=today()).sort((a,b)=>a.date.localeCompare(b.date))[0];if(upcoming){detail=`次の予定は ${upcoming.date}「${upcoming.title}」${upcoming.amount?` ${yen(upcoming.amount)}`:''}`;}if(state.balances.food<5000){tone='食費';title=`食費・日用品があと ${yen(state.balances.food)}`}else if(state.balances.pocket<3000){tone='お小遣い';title=`お小遣いがあと ${yen(state.balances.pocket)}`}return{tone,title,detail}}
function applyTheme(mode){const choice=mode||localStorage.getItem(THEME_KEY)||'system';localStorage.setItem(THEME_KEY,choice);const dark=choice==='dark'||(choice==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#0b1513':'#0f766e';return choice}
function parseShortcut(){const p=new URLSearchParams(location.search);if(!p.has('amount'))return null;const v=amount(p.get('amount'));if(v===null)return null;return{amount:v,category:p.get('category')||'食費・日用品',memo:(p.get('memo')||'').slice(0,80),date:safeDate(p.get('date'))||today(),source:p.get('source')||'shortcut'}}
function allocationPrompt(income){return `あなたは個人用お金管理AI「コンパス」です。次の入金の振り分けを提案してください。残高は勝手に変更しない。貯めることと生活を楽しむことの両立を重視してください。\n入金:${income}\n食費・日用品:${state.balances.food}\nお小遣い:${state.balances.pocket}\n目的別資金(名前|現在|目標|期限):\n${state.funds.map(f=>`${f.name}|${f.balance}|${f.target}|${f.deadline||'-'}`).join('\n')}\n\n最後に必ず次の形式で全項目を出してください。\n===OKANE_COMPASS_ALLOCATION===\n食費・日用品=\nお小遣い=\n${state.funds.map(f=>`${f.name}=`).join('\n')}\n未振り分け=\n===END_OKANE_COMPASS_ALLOCATION===`}
